import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DarkNavbar from '@/components/Header/DarkNavbar';

import LightNavbar from '@/components/Header/LightNavbar';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <DarkNavbar />

      <LightNavbar />
        {children}
      </body>
    </html>
  );
}
