import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";
import Footer from "@/components/Footer/Footer";

const mont = Montserrat({ subsets: ["latin"] });
import "./globals.css";
import DarkNavbar from '@/components/Header/DarkNavbar';

import LightNavbar from '@/components/Header/LightNavbar';
import { Import } from "lucide-react";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mont.className}>
      <DarkNavbar />

      <LightNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
